#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js
echo "bundling index.js ..."
./node_modules/.bin/browserify dist/index.js > dist/index.bundle.js
#./node_modules/.bin/browserify dist/index.js | \
#  ./node_modules/.bin/babel --no-babelrc --presets=env > dist/index.bundle.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "minifying index.bundle.js ..."
./node_modules/.bin/uglifyjs dist/index.bundle.js -m -c > dist/index.bundle.min.js
echo "done."
